#!/usr/bin/env bash
# Capture a reproducibility manifest of the host + both environments.
# Writes envs/system-manifest.txt (overwrites — the manifest describes "now";
# Git history preserves prior snapshots).
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/envs/system-manifest.txt"
QP="$ROOT/.venv-quant/bin/python"
SP="$ROOT/.venv-serve/bin/python"

{
echo "# System manifest — generated by scripts/capture_system_manifest.sh"
echo "utc_timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "hostname: $(hostname 2>/dev/null || echo unknown)"
echo "runpod_pod_id: ${RUNPOD_POD_ID:-unknown}"
echo
echo "## GPU"
nvidia-smi --query-gpu=name,memory.total,driver_version --format=csv,noheader 2>/dev/null \
    || echo "nvidia-smi unavailable"
echo "cuda_runtime (nvidia-smi header): $(nvidia-smi 2>/dev/null | grep -oP 'CUDA Version: \K[0-9.]+' || echo unknown)"
echo
echo "## Host"
echo "kernel: $(uname -r)"
echo "system_python: $(python3 --version 2>&1)"
echo "uv: $(uv --version 2>&1)"
echo
echo "## Git"
echo "commit: $(git -C "$ROOT" rev-parse HEAD 2>/dev/null || echo unknown)"
echo "branch: $(git -C "$ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
echo "dirty:  $(git -C "$ROOT" status --porcelain 2>/dev/null | wc -l) uncommitted paths"
echo
echo "## .venv-quant key versions"
if [[ -x "$QP" ]]; then
"$QP" - <<'EOF'
import importlib, importlib.metadata as md
for pkg in ("torch", "transformers", "datasets", "safetensors", "accelerate",
            "huggingface_hub", "kernels", "triton", "numpy", "pytest"):
    try:
        print(f"{pkg}: {md.version(pkg)}")
    except md.PackageNotFoundError:
        print(f"{pkg}: NOT INSTALLED")
import torch
print(f"torch.version.cuda: {torch.version.cuda}")
print(f"torch.cuda.is_available: {torch.cuda.is_available()}")
EOF
else
    echo "venv not bootstrapped"
fi
echo
echo "## .venv-serve key versions"
if [[ -x "$SP" ]]; then
"$SP" - <<'EOF'
import importlib.metadata as md
for pkg in ("vllm", "torch", "transformers", "openai", "aiohttp", "triton", "flashinfer-python"):
    try:
        print(f"{pkg}: {md.version(pkg)}")
    except md.PackageNotFoundError:
        print(f"{pkg}: NOT INSTALLED")
EOF
else
    echo "venv not bootstrapped"
fi
} > "$OUT"

echo "Manifest written to $OUT"
